module.exports = {
    "INVALID_ID": "Request id is invalid",
    "INVALID_PHONE": "Mobile number is invalid",
    "DATA_SAVED": "Data is saved",
    "DATA_FETCHED": "Data is fetched",
    "DATA_UPDATED": "Data is updated",
    "DATA_DELETED": "Data is updated",
    "NO_DATA_FOUND": "No data found",
    "EMPTY_OBJECT": "No data found for saving",
    "COMMON_ERROR": "Something went wrong",
    "SERVER_ERROR": "Something went wrong",
    "FETCHING_ERROR": "Something went wrong",
    "SAVING_ERROR": "Something went wrong",
    "UPDATING_ERROR": "Something went wrong",
    "DELETING_ERROR": "Something went wrong",
    "EXECUTION_ERROR": "Something went wrong",
    "OTP_SENT": "OTP is sent on your number",
    "OTP_VERIFIED": "OTP is verified",
    "INVALID_OTP": "OTP is not valid",
    "NO_SESSION_FOUND": "No session is found",
    "USER_ID_MISSING": "user id is missing",
    "TOKEN_ISSUER": "SERVER",
    "MOBILE_AUD": "APP",
    "WEB_AUD": "WEB",
    "TOKEN_EXPIRY_TIME": 10000,
    "REGISTERATION_SUCCESSFUl": "Registeration successful",
    "USED_SESSION": "Session already used",
}